export enum SimulatorStatus {
  UPLOADED = "UPLOADED",
  PARSING = "PARSING",
  REVIEW = "REVIEW",
  VALIDATED = "VALIDATED",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
  PROCESSING = "PROCESSING",
  FAILED = "FAILED",
}